import json
import pprint

spices = [  'paprika',
            'cayenne pepper',
            'chili powder',
            'curry powder',
            'vanilla extract',
            'vanilla bean',
            'kosher salt',
            'bay leaf',
            'crushed red pepper',
            'ginger',
            'baking powder',
            'baking soda',
            'cinnamon',
            'saffron',
            'mint',
            'tarragon',
            'chives',
            'fennel'
            'parsley',
            'sage',
            'allspice',
            'dill',
            'marjoram',
            'cumin',
            'oregano',
            'thyme',
            'rosemary',
            'basil',
            'tumeric',
            'cardamom',
            'nutmeg',
            'clove',
            'star anise',
            'anise',
            'basil',
            'smoked paprika',
            'garlic powder',
            'onion powder',
            'coriander',
            'black pepper',
            'peppercorns',
            'white pepper',
            'five spice',
            'mustard powder',
            'sesame seeds'      ]

oils = [    'sunflower oil',
            'peanut oil',
            'palm oil',
            'cottonseed oil',
            'olive oil',
            'extra virgin olive oil',
            'coconut oil',
            'corn oil'
            'sesame oil',
            'soybean oil',
            'vegetable oil',
            'rapeseed oil',
            'lard',
            'suet',             ]

milk =  [   'salted butter',
            'unsalted butter',
            'margarine',
            'buttermilk',
            'condensed milk'
            'custard',
            'dulce de leche',
            'evaporated milk',
            'frozen yogurt',
            'whole milk',
            'skim milk',
            'reduced fat milk',
            'whey'              ]

cream = [   'sour cream',
            'clotted cream',
            'cream'
            'whipped cream',
            'creme fraiche',
            'ice cream'         ]

yogurt = [  'yogurt',
            'greek yogurt',
            'plain yogurt'      ]

cheese = [  'cheddar cheese',
            'cream cheese',
            'goat cheese',
            'feta',
            'brie',
            'cream cheese',
            'cottage cheese',
            'mozzarella',
            'parmigiano-reggiano',
            'blue cheese',
            'gouda cheese',
            'american cheese',
            'camembert',
            'roquefort',
            'provolone',
            'gruyere cheese',
            'monterey jack',
            'stilton cheese',
            'gorgonzola',
            'emmental cheese',
            'ricotta',
            'swiss cheese'
            'colby cheese'
            'muenster cheese',
            'pecorino',
            'manchego',
            'edam',
            'halloumi',
            'havarti',
            'pecorino romano',
            'comte cheese',
            'grana',
            'asiago cheese'
            'pepper jack cheese'
            'mascarpone',
            'limburger',
            'American Cheese',
            'processed cheese'      ]

potatoes = ['potato',
            'sweet potato',
            'taro',
            'yam'
            'idaho potato',
            'russet potato',
            'yukon gold',
            'fingerlings'       ]

rice =  [   'brown rice',
            'white rice',
            'basmati',
            'wild rice',
            'jasmine rice',
            'glutinous rice'    ]

breads =  [ 'barley',
            'millet',
            'buckwheat',
            'corn',
            'oats',
            'steel-cut oats',
            'rolled oats',
            'instant oats',
            'quinoa',
            'rye',
            'sourdough',
            'white bread',
            'rye bread',
            'pita',
            'baguette',
            'focaccia',
            'naan',
            'banana bread',
            'bagel',
            'pumpernickel',
            'challah',
            'croissant',
            'english muffin',
            'raisin bread',
            'garlic bread',
            'biscuit',
            'bun',
            'hot dog bun',
            'hamburger bun'     ]

pastas = [  'angel hair',
            'linguine',
            'fettuccine',
            'orecchiette',
            'orzo',
            'rigatoni',
            'spaghetti',
            'fusilli',
            'farfalle',
            'penne'
            'tortellini',
            'rotelle',
            'lasagne',
            'vermicelli',
            'ramen',
            'soba',
            'udon',
            'rice vermicelli',
            'noodle'            ]

shrooms = [ 'shittake',
            'morel',
            'enokitake',
            'oyster mushroom',
            'white mushroom',
            'white button',
            'portobello'        ]

fruits = [  "apple",
            "pineapple",
            "grapefruit",
            "banana",
            "orange",
            "strawberry",
            "grape",
            "lemon",
            "cherry",
            "pear",
            "mango",
            "avocado",
            "peach",
            "melon",
            "apricot",
            "plum",
            "kiwi",
            'watermelon',
            'blackberry',
            'papaya',
            'cantaloupe',
            'berry',
            'tangerine',
            'coconut',
            'cranberry',
            'lychee',
            'date',
            'passion fruit'
            'gppseberry',
            'persimmon',
            'lime',
            "nectarine",
            "fig",
            "pomegranate"   ]

greens = [  'spinach',
            'kale',
            'cabbage',
            'broccoli',
            'dandelion',
            'leafy green',
            'chard',
            'lettuce',
            'rapini',
            'endive',
            'napa cabbage',
            'cauliflower',
            'tomato',
            'squash',
            'cucumber',
            'bell pepper',
            'pumpkin',
            'corn',
            'maize',
            'brussel sprout',
            'artichoke',
            'bell pepper',
            'chili pepper',
            'red pepper',
            'arugula',
            'watercress'
            'butternut squash',
            'eggplant']

legumes = [ 'bean',
            'soybean',
            'nut',
            'lentil',
            'pea',
            'okra',
            'green bean',
            'kidney bean',
            'navy bean',
            'pinto bean',
            'garbanzo bean',
            'wax bean',
            'mung bean',
            'snow pea',
            'lima pea'
            'alfalfa',
            'clover',
            'snap pea',
            'sugar snap pea',
            'snow pea',
            'peanut',
            'almond',
            'walnut',
            'cashew',
            'pecan',
            'pistachio',
            'hazelnut',
            'brazil nut',
            'pine nut',
            'macadamia',
            'chestnut'      ]


roots = [   'carrot',
            'parsnip',
            'turnip',
            'rutabaga',
            'radish',
            'celery',
            'daikon',
            'kohirabi',
            'scalllion',
            'jicama',
            'horseradish',
            'onion',
            'shallot',
            'vidalia onion',
            'red onion',
            'pearl onion',
            'leek',
            'water chestnut',
            'spring onion',
            'yellow onion',
            'white onion',
            'asparagus',
            'chicory',
            'garlic'        ]


eggs =  [   'egg',
            'chicken egg',
            'duck egg',
            'goose egg',
            'quail egg'     ]

lamb =  [   'lamb',
            'lamb chop',
            'lamb loin chop',
            'lamb rack',
            'rack of lamb',
            'lamb rib',
            'ground lamb',
            'lamb shank',
            'lamb sirloin',
            'boneless lamb leg',
            'bone-in lamb leg'  ]

pork =  [   'pork',
            'pork shoulder',
            'pork butt',
            'pork loin',
            'pork chop',
            'loin chop',
            'sirloin chop',
            'sirloin steak',
            'baby back rib',
            'riblet',
            'rack of pork',
            'pork loin half rib',
            'pork tenderloin',
            'sirloin roast',
            'spare rib',
            'pork sausage',
            'ground pork',
            'ham'               ]

beef =  [   'beef',
            't-bone steak',
            'strip steak',
            'chuck steak',
            'skirt steak',
            'brisket',
            'flank steak',
            'short loin',
            'flat iron steak',
            'short ribs',
            'rib eye steak',
            'rib steak',
            'round steak',
            'sirloin steak',
            'top sirloin',
            'bottom sirloin',
            'hanger steak',
            'beef tenderloin',
            'ground beef',
            'beef sausage'      ]

chicken = [ 'chicken',
            'chicken breast',
            'chicken wing',
            'chicken drum',
            'chicken drumstick',
            'chicken thigh',
            'chicken leg',
            'whole chicken',
            'chicken quarter',
            'whole chicken'     ]


pp = pprint.PrettyPrinter(indent=4)

with open("recipes.json", "rb") as jfile:
    j = json.load(jfile)


ingrd = dict()
for key, val in j.iteritems():
    ingrd[key] = val['ingredients']

pp.pprint(ingrd)


